spring:
  application:
    name: marketing-profile-api-server
  profiles:
    group:
      local: db-local
      prod: db-prod
      aws: db-aws
  config:
    import: "classpath:application-db.yaml"

debug: true

server:
  port: 8082
